const ACTION_PREFIX = '[PALETTES]';

export const PALETTES_ACTIONS = {
    FETCH_DATA_START: `${ACTION_PREFIX} FETCH_DATA_START`,
    FETCH_DATA_SUCCESS: `${ACTION_PREFIX} FETCH_DATA_SUCCESS`,
    FETCH_DATA_ERROR: `${ACTION_PREFIX} FETCH_DATA_ERROR`,

    SELECTED_PALETTE: `${ACTION_PREFIX} SELECTED_PALETTE`,
};