export const CREATE_PALETTE_ACTION = {
    CREATE_PALETTE: 'CREATE_PALETTE',
    EDIT_PALETTE: 'EDIT_PALETTE',
    SELECTED_PALETTE: 'SELECTED_PALETTE',
    PICKER_COMPLETED_COLOR: 'PICKER_COMPLETED_COLOR'
}