export const CREATE_GRADIENT_ACTION = {
    INITIATE_GRADIENT: 'INITIATE_GRADIENT',
    ADD_GRADIENT: 'ADD_GRADIENT',
    UPDATE_GRADIENT: 'UPDATE_GRADIENT',
    SLIDER_WIDTH: 'SLIDER_WIDTH',
    GRADIENT_ANGLE: 'GRADIENT_ANGLE',
    GRADIENT_CSS: 'GRADIENT_CSS',
    GRADIENT_TYPE: 'GRADIENT_TYPE',
    COLOR_CODE: 'COLOR_CODE',
    ACTIVE_COLOR: 'ACTIVE_COLOR',
    SELECTED_COLOR: 'SELECTED_COLOR',
    ACTIVE_INDEX: 'ACTIVE_INDEX',
    ACTIVE_COLOR_POSITION: 'ACTIVE_COLOR_POSITION',
}